openapi: 3.0.0

# Added by API Auto Mocking Plugin
servers:
  - description: SwaggerHub API Auto Mocking
    url: https://virtserver.swaggerhub.com/deterok/perx-go-test/1.0.0

info:
  description: This is an API of perx-go-test
  version: "1.0.0"
  title: Simple soft for generating keycodes
  contact:
    email: vsuharnikov@gmail.com
  license:
    name: MIT


paths:
  /codes:
    post:
      summary: generates a code
      operationId: genCode
      description: Generates a new code.
      responses:
        '201':
          description: code created
        '500':
          description: something is wrong

  /codes/check:
    post:
      summary: check a code
      operationId: addInventory
      description: |
        Check a code.

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/InventoryItem'

      responses:
        '201':
          description: code created
        '500':
          description: something is wrong


components:
  schemas:
    InventoryItem:
      type: object
      required:
        - id
        - name
        - manufacturer
        - releaseDate
      properties:
        id:
          type: string
          format: uuid
          example: d290f1ee-6c54-4b01-90e6-d701748f0851
        name:
          type: string
          example: Widget Adapter
        releaseDate:
          type: string
          format: date-time
          example: '2016-08-29T09:12:33.001Z'
        manufacturer:
          $ref: '#/components/schemas/Manufacturer'
    Manufacturer:
      required:
        - name
      properties:
        name:
          type: string
          example: ACME Corporation
        homePage:
          type: string
          format: url
          example: 'https://www.acme-corp.com'
        phone:
          type: string
          example: 408-867-5309
      type: object
